# Generated by Django 2.1.4 on 2018-12-29 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 29, 17, 51, 15, 539809), verbose_name='date published'),
        ),
    ]
