# Generated by Django 2.1.4 on 2018-12-29 23:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20181229_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 30, 0, 11, 0, 808262), verbose_name='date published'),
        ),
    ]
